name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - features/criando-arquivo-github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/{{ secrets.DOCKERHUB_REPO }}:latest .
      - name: Publish
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/{{ secrets.DOCKERHUB_REPO }}:latest
