name: Build and Push Docker Image
on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          docker build . -t satdoug/lab365-timer:latest
      - name: Publish
        run: |
          docker login -u satdoug -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push satdoug/lab365-timer:latest
